version: '3.8'

services:
  sistema-bancario-api:
    # Use a imagem publicada no Docker Hub
    # Substitua 'seu-usuario' pelo seu nome de usuário real
    image: seu-usuario/sistema-bancario-api:latest
    
    # Ou para build local descomente a linha abaixo e comente a linha 'image'
    # build: .
    
    container_name: sistema-bancario-api
    
    ports:
      - "8080:8080"
    
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    
    # Logs configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

# Opcional: Network customizada
networks:
  default:
    name: sistema-bancario-network
